### ISSUE TITLE
"Can't go to checkout. Please try again."

### ISSUE THREAD

**Issue by ohsnapitscolin** [ticketmaster/ReactNative-TicketmasterDemoIntegration#14]
When testing with the Purchase and PrePurchase activities, I'm getting an error when I try to proceed to checkout. The is on a build that is unchanged from the `main` branch.

https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/assets/5816480/9e9cf1b7-ccff-46a4-92f3-6c1f27afedf6

**Comment by TakaGoto** [comment]
we have a fix for this but its not released yet. you can use `2.0.0-CHECKOUT-FIX-SNAPSHOT` in the meantime:

```
implementation "com.ticketmaster.retail:purchase:2.0.0-CHECKOUT-FIX-SNAPSHOT"
```

**Comment by ohsnapitscolin** [comment]
Hey @TakaGoto, just tested this out, everything's looking good. Will be on the lookout for the release with the official fix:
https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/assets/5816480/3c00f503-4345-42d7-a2ff-afe0985e3969

**Comment by joe-goodall-ticketmaster** [comment]
Hey @ohsnapitscolin 
Sorry for the delay on this. The fix is now included in the latest code on main.
Let us know if you continue to see issues.
